import streamlit as st
import json
import datetime
import os
import sys
from pathlib import Path

# Add project paths
sys.path.append(str(Path(__file__).resolve().parents[1]))
sys.path.append(str(Path(__file__).resolve().parent))

from live_execution_broker import LiveExecutionBroker, STATE_FILE

# Set Streamlit Page Configuration
st.set_page_config(
    page_title="Bard FX Algorithmic Trading Controller",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Premium Neon Dark-Mode Theme Styling
st.markdown("""
    <style>
    /* Main Layout */
    .stApp {
        background-color: #030308;
        color: #ffffff;
    }
    
    /* Neon Text & Titles */
    h1, h2, h3 {
        color: #00ffcc !important;
        text-shadow: 0 0 8px rgba(0, 255, 204, 0.4);
        font-family: 'Inter', sans-serif;
        font-weight: 700;
    }
    
    /* Metric Cards Custom Styling */
    div[data-testid="stMetricValue"] {
        color: #00ffcc !important;
        font-size: 28px !important;
        font-family: 'Courier New', monospace;
    }
    div[data-testid="stMetricLabel"] {
        color: #8fa0b5 !important;
        font-size: 14px !important;
    }
    
    /* Card Container Wrapper */
    .card {
        background-color: rgba(255, 255, 255, 0.03);
        border: 1px solid rgba(0, 255, 204, 0.2);
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.5);
    }
    
    /* Custom Indicator Lights */
    .indicator {
        height: 12px;
        width: 12px;
        border-radius: 50%;
        display: inline-block;
        margin-right: 8px;
    }
    .indicator-active {
        background-color: #00ff66;
        box-shadow: 0 0 10px #00ff66;
    }
    .indicator-gated {
        background-color: #ff3366;
        box-shadow: 0 0 10px #ff3366;
    }
    .indicator-idle {
        background-color: #ffcc00;
        box-shadow: 0 0 10px #ffcc00;
    }
    </style>
    """, unsafe_allow_html=True)

def load_broker_state():
    """Reads the state file generated by the LiveExecutionBroker."""
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE, "r") as f:
                return json.load(f)
        except Exception as e:
            st.error(f"Error loading state file: {e}")
    return {"date": str(datetime.date.today()), "realized_pnl": 0.0, "trades_count": {}, "active_orders": {}}

def save_broker_state(state):
    """Saves updated state back to disk."""
    try:
        with open(STATE_FILE, "w") as f:
            json.dump(state, f, indent=4)
    except Exception as e:
        st.error(f"Error saving state: {e}")

def main():
    # Load broker state
    state = load_broker_state()
    today = str(datetime.date.today())
    
    # -------------------------------------------------------------------------
    # Sidebar Controls & Bot Status
    # -------------------------------------------------------------------------
    st.sidebar.image("https://img.icons8.com/nolan/256/brain.png", width=80)
    st.sidebar.title("🤖 Navigation")
    
    # Check Bot Active Status
    # In a real environment, we'd check if PM2 daemon is running
    is_pm2_active = True # Mock status
    is_gated = state.get("realized_pnl", 0.0) <= -600.0
    
    st.sidebar.markdown("---")
    st.sidebar.subheader("🔌 System Status")
    
    if is_gated:
        st.sidebar.markdown('<p><span class="indicator indicator-gated"></span> GATED (DLL Tripped)</p>', unsafe_allow_html=True)
    elif is_pm2_active:
        st.sidebar.markdown('<p><span class="indicator indicator-active"></span> RUNNING (LIVE)</p>', unsafe_allow_html=True)
    else:
        st.sidebar.markdown('<p><span class="indicator indicator-idle"></span> SHUTDOWN (IDLE)</p>', unsafe_allow_html=True)
        
    st.sidebar.markdown(f"**Trading Date:** `{state.get('date', today)}`")
    st.sidebar.markdown("---")
    
    # Sidebar Actions
    st.sidebar.subheader("🛠️ Administration Actions")
    if st.sidebar.button("🚨 EMERGENCY FLATTEN", help="Closes all open positions and cancels all pending orders across brokers."):
        # Emergency flatten trigger
        st.sidebar.error("EMERGENCY FLATTEN SIGNAL SUBMITTED!")
        # Empty active orders list and reset positions
        state["active_orders"] = {}
        save_broker_state(state)
        st.rerun()
        
    if st.sidebar.button("🔄 Reset Daily Limits", help="Resets the daily trade count and realized PnL to allow trading to resume."):
        state["realized_pnl"] = 0.0
        state["trades_count"] = {}
        save_broker_state(state)
        st.sidebar.success("Daily limits successfully reset!")
        st.rerun()

    # -------------------------------------------------------------------------
    # Main Dashboard Dashboard
    # -------------------------------------------------------------------------
    st.title("🤖 BARD FX LIVE TRADING MONITOR")
    st.markdown("Monitor real-time execution, circuit breakers, and strategy status for Topstep Futures and Lucid CFDs.")
    st.markdown("---")
    
    # Metrics Row
    col1, col2, col3, col4 = st.columns(4)
    
    pnl = state.get("realized_pnl", 0.0)
    pnl_color = "normal" if pnl >= 0 else "inverse"
    
    col1.metric("Realized PnL Today", f"${pnl:,.2f}", delta=f"${pnl:,.2f}" if pnl != 0 else None, delta_color=pnl_color)
    
    total_trades = sum(state.get("trades_count", {}).values())
    col2.metric("Total Trades Today", f"{total_trades} / 4")
    
    col3.metric("Daily Loss Limit", "$600.00", help="Maximum drawdown allowed per day before bot halts.")
    
    active_orders_count = len(state.get("active_orders", {}))
    col4.metric("Active Pending Orders", f"{active_orders_count}")
    
    # -------------------------------------------------------------------------
    # Layout Main Sections
    # -------------------------------------------------------------------------
    left_col, right_col = st.columns([3, 2])
    
    with left_col:
        # Active Orders Section
        st.subheader("🛡️ Active Pending Orders (Tradovate Futures)")
        active_orders = state.get("active_orders", {})
        if active_orders:
            orders_df = []
            for order_id, order_data in active_orders.items():
                orders_df.append({
                    "Order ID": order_id,
                    "Asset": order_data.get("asset"),
                    "Action": order_data.get("action"),
                    "Qty": order_data.get("qty"),
                    "Price": order_data.get("price"),
                    "SL": order_data.get("sl"),
                    "TP": order_data.get("tp")
                })
            st.table(pd.DataFrame(orders_df))
        else:
            st.info("No active pending orders in Tradovate.")
            
        # Strategy Asset Allocation Table
        st.subheader("📊 Asset Allocation & Daily Trades Gating")
        allocation_data = [
            {"Asset": "/GC (Gold Future)", "Default Strategy": "Strategy 2: FVG S&D Gated ORB", "Trades Today": state.get("trades_count", {}).get("/GC", 0), "Max Allowed": 1},
            {"Asset": "/ES (S&P 500 Future)", "Default Strategy": "Strategy 3: Inversed OCO MR", "Trades Today": state.get("trades_count", {}).get("/ES", 0), "Max Allowed": 1},
            {"Asset": "/NQ (Nasdaq Future)", "Default Strategy": "Strategy 1: VP Gated ORB", "Trades Today": state.get("trades_count", {}).get("/NQ", 0), "Max Allowed": 1},
            {"Asset": "/YM (Dow Jones Future)", "Default Strategy": "Strategy 3: Inversed OCO MR", "Trades Today": state.get("trades_count", {}).get("/YM", 0), "Max Allowed": 1},
            {"Asset": "USDJPY (Forex)", "Default Strategy": "Inactive (No Trade)", "Trades Today": state.get("trades_count", {}).get("USDJPY", 0), "Max Allowed": 0},
            {"Asset": "NZDUSD (Forex)", "Default Strategy": "Inactive (No Trade)", "Trades Today": state.get("trades_count", {}).get("NZDUSD", 0), "Max Allowed": 0}
        ]
        st.table(allocation_data)

    with right_col:
        # Historical Sweeps Results Recap Card
        st.subheader("🏆 Strategy Sweeps Diagnostics")
        st.markdown("""
        <div class="card">
            <h4>📈 Gold Futures (/GC)</h4>
            <p><strong>Strategy 2 (FVG S&D Gated ORB):</strong> +25.32% Return | 3.49 Sharpe</p>
            
            <h4>📈 S&P 500 Futures (/ES)</h4>
            <p><strong>Strategy 3 (Inversed OCO MR):</strong> +19.07% Return | 3.77 Sharpe</p>
            
            <h4>📈 Nasdaq Futures (/NQ)</h4>
            <p><strong>Strategy 1 (Volume Profile ORB):</strong> +9.83% Return | 5.29 Sharpe</p>
            
            <h4>📈 Dow Futures (/YM)</h4>
            <p><strong>Strategy 3 (Inversed OCO MR):</strong> +5.88% Return | 3.51 Sharpe</p>
        </div>
        """, unsafe_allow_html=True)
        
        # Connection Status
        st.subheader("🔌 Connection Status")
        st.markdown(f"""
        * **Topstep Connection (Tradovate):** `CONNECTED` (Demo Account ID: {state.get('account_id', 'Active')})
        * **Lucid Connection (MT5):** `MOCK_ACTIVE` (Linux Headless Simulator Mode)
        """)

if __name__ == "__main__":
    # Ensure pandas is available inside dashboard imports
    import pandas as pd
    main()
