#!/usr/bin/env python3
"""Auto-generated runner for strategy: breakout_pct_003.

Generated by runners/generate_runners.py. Do not hand-edit; regenerate instead.

This runner trades BTC, ETH, SOL, BNB, XRP, and HYPE UP/DOWN markets with
per-asset portfolios, capital pools, and log files.
"""

import os
import sys
import time
import signal
import math
import json
import statistics
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from engine.strategy_registry import STRATEGIES
from signals.breakout_pct_003 import breakout_pct_003_signal
try:
    from signals.breakout_pct_003 import warm_start as _signal_warm_start
except Exception:
    # Optional restart-resilience hook. Only daily_orb_v5 provides it today;
    # every other signal module simply no-ops here.
    _signal_warm_start = None
from engine.capital import GlobalCapitalPool
from engine.discovery import discover_asset_markets
from engine.execution import (
    MIN_CONTRACTS,
    QUEUE_FILL_FRACTION,
    RISK_PCT,
    position_notional,
)
from engine.feed import RedisFeed
from engine.portfolio import Portfolio, EXIT_SNIPE_PRICE
from engine.logger import StrategyLogger

STRATEGY_NAME = 'breakout_pct_003'
SAFE_NAME = 'breakout_pct_003'

# Sizing & risk constants (per SPEC).
CAPITAL = 200.0
RISK_PCT = 0.005
MIN_CONTRACTS = 5
# Real-only orderbook wait on entry: when a signal fires but the real
# multi-level book is momentarily missing (thin-token TTL blink / short WS
# reconnect gap), briefly re-poll latest_book_real before giving up. No
# synthetic fallback is ever used, so fills stay 100% real. BOOK_WAIT_SEC is
# the max per-signal wait; BOOK_WAIT_POLL_SECONDS is the re-poll cadence.
BOOK_WAIT_SEC = 2.0
BOOK_WAIT_POLL_SECONDS = 0.1
DEFAULT_MAX_ENTRY_PRICE = 0.85
LOOP_SLEEP_SECONDS = 0.25
DISCOVERY_INTERVAL_SECONDS = 30.0
SPOT_HISTORY_MAX_LEN = 1000

# Assets to trade. BTC keeps the legacy name (e.g. ``breakout``); others append
# the asset suffix (e.g. ``breakout_eth``) so history/state remain separate.
ASSETS = ["BTC", "ETH", "SOL", "BNB", "XRP", "HYPE"]

# Diagnostic heartbeat interval. We emit a structured heartbeat event even when
# no trades occur so operators can tell a runner is alive (and not hung).
HEARTBEAT_INTERVAL_SECONDS = 30.0

_running = True


def _handle_signal(signum, frame):
    global _running
    _running = False


signal.signal(signal.SIGTERM, _handle_signal)
signal.signal(signal.SIGINT, _handle_signal)


def _now_utc():
    return datetime.now(timezone.utc)


def _asset_safe_name(asset: str) -> str:
    """Return the logger/portfolio name for this asset."""
    asset = asset.upper()
    if asset == "BTC":
        return SAFE_NAME
    return f"{SAFE_NAME}_{asset.lower()}"


def _compute_z_score(prices, window=20):
    """Rolling z-score of the latest price versus the recent window."""
    if len(prices) < 2:
        return 0.0
    recent = prices[-window:] if len(prices) >= window else prices
    mean = statistics.mean(recent)
    if len(recent) < 2:
        return 0.0
    std = statistics.stdev(recent)
    if std == 0.0:
        return 0.0
    return (prices[-1] - mean) / std


def _compute_velocity(prices):
    """Return current velocity, std of velocity, and velocity history."""
    if len(prices) < 2:
        return 0.0, 0.0, []
    v_t = prices[-1] - prices[-2]
    history = [prices[i] - prices[i - 1] for i in range(1, len(prices))]
    std_v = statistics.stdev(history) if len(history) > 1 else 0.0
    return v_t, std_v, history


def _compute_acceleration(velocity_history):
    """Second difference of price (change in velocity)."""
    if len(velocity_history) < 2:
        return 0.0
    return velocity_history[-1] - velocity_history[-2]


def _compute_tick_change(prices):
    if len(prices) < 2:
        return 0.0
    return prices[-1] - prices[-2]


def _compute_spread(yes_ask, yes_bid, no_ask, no_bid):
    """Return yes/no mids and spread aliases used by different signals."""
    yes_mid = (yes_ask + yes_bid) / 2.0 if yes_ask is not None and yes_bid is not None else 0.0
    no_mid = (no_ask + no_bid) / 2.0 if no_ask is not None and no_bid is not None else 0.0
    spread = (yes_ask - yes_bid) if yes_ask is not None and yes_bid is not None else 0.0
    return yes_mid, no_mid, spread, spread


def _rem_sec_from_market(market):
    """Seconds remaining until market expiry."""
    end_iso = market.get("end_date_iso")
    if not end_iso:
        return 0.0
    try:
        end = datetime.fromisoformat(end_iso.replace("Z", "+00:00"))
        return max(0.0, (end - _now_utc()).total_seconds())
    except Exception:
        return 0.0


def _load_portfolio_state(portfolio, logger):
    """Restore portfolio from the last persisted state so restarts are seamless."""
    try:
        state_path = Path(logger._state_path)
        if state_path.exists():
            with open(state_path, "r", encoding="utf-8") as fh:
                state = json.load(fh)
            portfolio.load_state(state)
            logger.log_event("state_loaded", {
                "active": portfolio.perf().get("active_count", 0),
                "closed": portfolio.perf().get("closed_count", 0),
                "pnl": portfolio.perf().get("total_pnl", 0.0),
            })
    except Exception as exc:
        logger.log_event("state_load_error", {"error": str(exc)})


def _build_signal_kwargs(registry_entry, market, state):
    """Build kwargs dict matching exactly the params requested by the strategy."""
    params = list(registry_entry.get("params", []))
    spot_history = state["spot_history"]
    spot_price = state["spot_price"]
    # For UP/DOWN markets the "strike" is the window-open Chainlink oracle price.
    # Fall back to the legacy textual strike, then to current spot only if neither
    # is available.
    strike = market.get("open_oracle_price") or market.get("strike") or spot_price
    rem_sec = state["rem_sec"]
    yp = state["yp"]
    np_val = state["np_val"]
    yes_ask = state["yes_ask"]
    yes_bid = state["yes_bid"]
    no_ask = state["no_ask"]
    no_bid = state["no_bid"]

    z_score = _compute_z_score(spot_history)
    v_t, std_v, velocity_history = _compute_velocity(spot_history)
    a_t = _compute_acceleration(velocity_history)
    tick_change = _compute_tick_change(spot_history)
    _, _, spread, spread_val = _compute_spread(yes_ask, yes_bid, no_ask, no_bid)
    z_dist = abs(z_score)

    # Timeframe hint: registry override, then market duration, then infer from rem_sec.
    tf_hint = registry_entry.get("tf_hint") or market.get("duration")
    if tf_hint is None:
        tf_hint = "15m" if rem_sec > 500 else "5m"

    # ORB / re-entry parameters come from registry so each variant gets its own tuning.
    or_window_seconds = registry_entry.get("or_window_seconds")
    max_reentries = registry_entry.get("_max_reentries") or registry_entry.get("max_reentries")

    param_map = {
        "spot_price": spot_price,
        "strike": strike,
        "z_score": z_score,
        "rem_sec": rem_sec,
        "yp": yp,
        "np_val": np_val,
        "v_t": v_t,
        "std_v": std_v,
        "a_t": a_t,
        "spread": spread,
        "spread_val": spread_val,
        "tick_change": tick_change,
        "velocity_history": velocity_history,
        "z_dist": z_dist,
        "yes_ask": yes_ask,
        "no_ask": no_ask,
        "tf_hint": tf_hint,
        "market_id": market.get("condition_id"),
        "max_entry_price": DEFAULT_MAX_ENTRY_PRICE,
        "or_window_seconds": or_window_seconds,
        "max_reentries": max_reentries,
        # Forward the market's underlying asset (default BTC for legacy signals).
        "asset": market.get("asset") or "BTC",
        # Provenance fields from discovery; only injected if a signal requests them.
        "start_date_iso": market.get("start_date_iso"),
        "resolution_source": market.get("resolution_source"),
    }

    kwargs = {}
    for p in params:
        kwargs[p] = param_map.get(p)
    return kwargs


class AssetRunner:
    """One runner instance per asset, with isolated portfolio/pool/logger."""

    def __init__(self, asset: str, registry_entry: dict):
        self.asset = asset.upper()
        self.registry_entry = registry_entry
        self.name = _asset_safe_name(self.asset)
        # Per-asset namespace so BTC capital is not shared with ETH.
        # Per-strategy per-asset namespace so breakout_eth and rsi2_eth do not
        # share the same $200 pool.
        self.namespace = f"paper:{self.asset.lower()}:{SAFE_NAME}"
        self.portfolio = Portfolio(name=self.name, capital=CAPITAL)
        self.global_pool = GlobalCapitalPool(total_capital=CAPITAL, namespace=self.namespace)
        self.logger = StrategyLogger(name=self.name)
        self.markets: list = []
        self.spot_history: list = []
        self.oracle_spot: float | None = None
        self.last_discovery = 0.0
        self.last_heartbeat = 0.0
        self.diag = {
            "signals_seen": 0,
            "signals_triggered": 0,
            "fills_attempted": 0,
            "fills_succeeded": 0,
            "trades_opened": 0,
            "errors": 0,
            "markets_processed": 0,
        }
        _load_portfolio_state(self.portfolio, self.logger)
        # Restart resilience: recover the daily opening range + re-entry state so
        # a restart trades exactly as if it had been alive since the 9:30 ET open.
        # No-ops for signals without warm_start (everything except daily_orb_v5).
        if _signal_warm_start is not None:
            try:
                _ws_tf = self.registry_entry.get("tf_hint") or "any"
                _ws_re = self.registry_entry.get("_max_reentries") or self.registry_entry.get("max_reentries", 0)
                _ws_report = _signal_warm_start(self.asset, _ws_tf, _ws_re)
                self.logger.log_event("warm_start", {
                    "strategy": STRATEGY_NAME,
                    "asset": self.asset,
                    "report": _ws_report,
                })
            except Exception as _ws_exc:
                self.logger.log_event("warm_start_error", {
                    "strategy": STRATEGY_NAME,
                    "asset": self.asset,
                    "error": str(_ws_exc),
                })
        self.logger.log_event("runner_startup", {
            "strategy": STRATEGY_NAME,
            "safe_name": SAFE_NAME,
            "asset": self.asset,
            "name": self.name,
            "capital": CAPITAL,
            "risk_pct": RISK_PCT,
            "namespace": self.namespace,
        })

    def _maybe_capture_open_oracle(self, feed: RedisFeed, market: dict) -> None:
        """Capture the Chainlink oracle at window-open if it wasn't available at discovery.

        UP/DOWN markets may be discovered before their window opens.  Once the
        window has opened we snapshot the current Chainlink oracle as the
        market-open reference and persist it on the market dict.
        """
        if market.get("open_oracle_price") is not None:
            return
        start_iso = market.get("start_date_iso")
        if not start_iso:
            return
        try:
            start_dt = datetime.fromisoformat(str(start_iso).replace("Z", "+00:00"))
        except (ValueError, TypeError):
            return
        if datetime.now(timezone.utc) < start_dt:
            return
        try:
            price = feed.latest_oracle_price(self.asset)
            if price and price > 0.0:
                market["open_oracle_price"] = float(price)
        except Exception:
            pass

    def discover(self, feed: RedisFeed):
        try:
            self.markets = discover_asset_markets(asset=self.asset)
            # Backfill window-open prices for markets whose window opened before
            # we had Chainlink history at discovery time.
            for market in self.markets:
                self._maybe_capture_open_oracle(feed, market)
        except Exception as exc:
            self.logger.log_event("discovery_error", {"error": str(exc), "asset": self.asset})
            self.diag["errors"] += 1
            self.markets = []
        self.last_discovery = time.time()
        self.logger.log_event("discovery", {"markets": len(self.markets), "asset": self.asset})

    def update_spot(self, feed: RedisFeed):
        try:
            price = feed.latest_spot_price(self.asset)
        except Exception as exc:
            self.logger.log_event("feed_spot_error", {"error": str(exc), "asset": self.asset})
            price = None
        if price and price > 0.0:
            self.spot_history.append(float(price))
            if len(self.spot_history) > SPOT_HISTORY_MAX_LEN:
                self.spot_history = self.spot_history[-SPOT_HISTORY_MAX_LEN:]

    def update_oracle(self, feed: RedisFeed):
        """Fetch the Chainlink RTDS oracle spot used for expiry resolution."""
        try:
            price = feed.latest_oracle_price(self.asset)
        except Exception as exc:
            self.logger.log_event("feed_oracle_error", {"error": str(exc), "asset": self.asset})
            price = None
        if price and price > 0.0:
            self.oracle_spot = float(price)

    def heartbeat(self):
        perf = self.portfolio.perf()
        self.logger.log_event("runner_heartbeat", {
            "asset": self.asset,
            "markets": len(self.markets),
            "spot": self.spot_history[-1] if self.spot_history else None,
            "spot_history": len(self.spot_history),
            "active_trades": perf.get("active_count", 0),
            "closed_trades": perf.get("closed_count", 0),
            "total_pnl": perf.get("total_pnl", 0.0),
            "diag": dict(self.diag),
        })
        for key in self.diag:
            self.diag[key] = 0
        self.last_heartbeat = time.time()

    def process_markets(self, feed: RedisFeed):
        if not self.spot_history:
            return
        spot_price = float(self.spot_history[-1])

        for market in self.markets:
            if not _running:
                break
            self.diag["markets_processed"] += 1

            try:
                # Capture the window-open oracle price once the market window opens.
                self._maybe_capture_open_oracle(feed, market)

                token_yes = market.get("token_id_yes")
                token_no = market.get("token_id_no")
                if not token_yes or not token_no:
                    continue

                yes_prices = feed.latest_prices(token_yes)
                no_prices = feed.latest_prices(token_no)

                yp = (yes_prices.get("bid") or 0.0) if yes_prices else 0.0
                yes_ask = (yes_prices.get("ask") or 1.0) if yes_prices else 1.0
                np_val = (no_prices.get("bid") or 0.0) if no_prices else 0.0
                no_ask = (no_prices.get("ask") or 1.0) if no_prices else 1.0

                rem_sec = _rem_sec_from_market(market)
                if rem_sec <= 0:
                    continue

                state = {
                    "spot_price": spot_price,
                    "spot_history": self.spot_history,
                    "rem_sec": rem_sec,
                    "yp": yp,
                    "np_val": np_val,
                    "yes_ask": yes_ask,
                    "yes_bid": yp,
                    "no_ask": no_ask,
                    "no_bid": np_val,
                }

                oracle_spot = self.oracle_spot
                try:
                    closed_trades = self.portfolio.check_exits(
                        spot_price, yp, np_val, rem_sec, oracle_spot=oracle_spot
                    )
                    for closed in closed_trades:
                        net_proceeds = closed.exit_price * closed.net_shares() - closed.exit_fee
                        self.global_pool.release(net_proceeds)
                        self.logger.log_trade(closed.to_dict())
                        self.logger.write_state(self.portfolio.state())
                        self.logger.write_perf(self.portfolio.perf())
                except Exception as exc:
                    self.logger.log_event("check_exits_error", {
                        "error": str(exc),
                        "market": market.get("condition_id"),
                        "asset": self.asset,
                    })
                    self.diag["errors"] += 1

                kwargs = _build_signal_kwargs(self.registry_entry, market, state)
                sig = breakout_pct_003_signal(**kwargs)
                self.diag["signals_seen"] += 1

                if sig and sig.get("triggered"):
                    self.diag["signals_triggered"] += 1
                    direction = sig.get("direction")
                    if direction not in ("YES", "NO"):
                        self.logger.log_event("signal_invalid_direction", {
                            "direction": direction,
                            "market": market.get("condition_id"),
                            "asset": self.asset,
                        })
                        continue

                    entry_price = float(sig.get("entry_price") or 0.0)
                    target_notional = position_notional(
                        capital=self.global_pool.available(),
                        entry_price=entry_price,
                        risk_pct=RISK_PCT,
                        min_contracts=MIN_CONTRACTS,
                    )
                    if target_notional <= 0:
                        continue
                    # Fees are deducted in shares, not added to the USDC cost, so we
                    # reserve only the gross notional from the shared capital pool.
                    requested = target_notional
                    approved = self.global_pool.request(requested)
                    self.logger.log_event("capital_request", {
                        "strategy": STRATEGY_NAME,
                        "asset": self.asset,
                        "market": market.get("condition_id"),
                        "direction": direction,
                        "requested": round(requested, 4),
                        "approved": round(approved, 4),
                    })
                    if approved <= 0:
                        self.logger.log_event("signal_no_capital", {
                            "strategy": STRATEGY_NAME,
                            "asset": self.asset,
                            "market": market.get("condition_id"),
                            "direction": direction,
                        })
                        continue

                    trade = None
                    try:
                        token = market.get("token_id_yes") if direction == "YES" else market.get("token_id_no")
                        book = feed.latest_book_real(token) if token else None
                        latency_book = feed.latency_book(token) if token else None
                        # Real-only orderbook wait: briefly re-poll the REAL book
                        # (never synthetic) if it is missing/thin on first look.
                        # Capital is still released in `finally` if no book arrives
                        # because `trade` stays None on the signal_no_book path.
                        if (not book or not book.get("asks")) and token:
                            _wait_deadline = time.time() + BOOK_WAIT_SEC
                            while time.time() < _wait_deadline:
                                time.sleep(BOOK_WAIT_POLL_SECONDS)
                                book = feed.latest_book_real(token)
                                if book and book.get("asks"):
                                    latency_book = feed.latency_book(token)
                                    break
                        if not book or not book.get("asks"):
                            self.logger.log_event("signal_no_book", {
                                "direction": direction,
                                "market": market.get("condition_id"),
                                "asset": self.asset,
                            })
                            continue

                        fair_price = None
                        if yes_ask is not None and yp is not None and yes_ask > 0 and yp > 0:
                            fair_price = (yes_ask + yp) / 2.0
                        if direction == "NO" and no_ask is not None and np_val is not None and no_ask > 0 and np_val > 0:
                            fair_price = (no_ask + np_val) / 2.0

                        self.diag["fills_attempted"] += 1
                        self.logger.log_event("signal_trigger", {
                            "strategy": STRATEGY_NAME,
                            "asset": self.asset,
                            "market": market.get("condition_id"),
                            "direction": direction,
                        })

                        _cid = market.get("condition_id")
                        _existing = self.portfolio.active_trades.get(_cid)
                        _scale_in = bool(self.registry_entry.get("scale_in", False))
                        _max_adds = int(self.registry_entry.get("max_adds", 0) or 0)
                        # Scale-in (same-direction "double down"): if this variant
                        # enables it and we already hold the same direction on this
                        # contract with adds remaining, merge more size into the
                        # open trade instead of opening a fresh/re-entry position.
                        _can_scale = (
                            _scale_in and _existing is not None
                            and _existing.direction == direction
                            and self.portfolio.add_count(_cid) < _max_adds
                        )
                        _pre_notional = 0.0
                        if _can_scale:
                            _pre_notional = _existing.entry_notional
                            trade = self.portfolio.scale_in(
                                sig,
                                market,
                                book,
                                entry_spot=spot_price,
                                latency_book=latency_book,
                                fair_price=fair_price,
                                queue_fraction=QUEUE_FILL_FRACTION,
                                max_notional=approved,
                                max_adds=_max_adds,
                            )
                        else:
                            trade = self.portfolio.check_entry(
                                sig,
                                market,
                                book,
                                entry_spot=spot_price,
                                latency_book=latency_book,
                                fair_price=fair_price,
                                queue_fraction=QUEUE_FILL_FRACTION,
                                max_notional=approved,
                                allow_reentry=bool(self.registry_entry.get("allow_reentry", False)),
                                max_reentries=self.registry_entry.get("_max_reentries") or self.registry_entry.get("max_reentries", 0),
                            )
                        if trade is None:
                            continue
                    except Exception as exc:
                        self.logger.log_event("check_entry_error", {
                            "error": str(exc),
                            "market": market.get("condition_id"),
                            "asset": self.asset,
                        })
                        self.diag["errors"] += 1
                        continue
                    finally:
                        if trade is None and approved > 0:
                            self.logger.log_event("capital_release", {
                                "strategy": STRATEGY_NAME,
                                "asset": self.asset,
                                "market": market.get("condition_id"),
                                "amount": round(approved, 4),
                                "reason": "entry_failed",
                            })
                            self.global_pool.release(approved)

                    # With share-deduction fee model the USDC paid equals the
                    # gross notional; the fee is paid in reduced share count.
                    # For a scale-in add, actual_cost is the INCREMENTAL notional
                    # of this add (post - pre), not the cumulative position total.
                    if _can_scale:
                        actual_cost = max(0.0, trade.entry_notional - _pre_notional)
                    else:
                        actual_cost = trade.entry_notional
                    self.logger.log_event("capital_reserved", {
                        "strategy": STRATEGY_NAME,
                        "asset": self.asset,
                        "market": market.get("condition_id"),
                        "approved": round(approved, 4),
                        "actual_cost": round(actual_cost, 4),
                        "excess": round(max(0.0, approved - actual_cost), 4),
                        "scale_in": bool(_can_scale),
                    })
                    if approved > actual_cost:
                        try:
                            self.logger.log_event("capital_release", {
                                "strategy": STRATEGY_NAME,
                                "asset": self.asset,
                                "market": market.get("condition_id"),
                                "amount": round(approved - actual_cost, 4),
                                "reason": "excess_reservation",
                            })
                            self.global_pool.release(approved - actual_cost)
                        except Exception as exc:
                            self.logger.log_event("capital_release_error", {
                                "error": str(exc),
                                "amount": approved - actual_cost,
                                "asset": self.asset,
                            })

                    self.diag["fills_succeeded"] += 1
                    if _can_scale:
                        self.diag["scale_ins"] = self.diag.get("scale_ins", 0) + 1
                    else:
                        self.diag["trades_opened"] += 1
                    self.logger.log_trade(trade.to_dict())
                    self.logger.write_state(self.portfolio.state())
                    self.logger.write_perf(self.portfolio.perf())

            except Exception as exc:
                self.logger.log_event("market_loop_error", {
                    "error": str(exc),
                    "market": market.get("condition_id") if isinstance(market, dict) else None,
                    "asset": self.asset,
                })
                self.diag["errors"] += 1

    def resolve_dropped_markets(self, feed: RedisFeed):
        """Close positions whose markets expired and dropped out of discovery."""
        if not self.spot_history:
            return
        try:
            current_condition_ids = {
                m.get("condition_id") for m in self.markets if m.get("condition_id")
            }
            # Prefer Chainlink oracle for expiry resolution; Hyperliquid spot as fallback.
            spot = self.oracle_spot if self.oracle_spot is not None else float(self.spot_history[-1])
            for condition_id in list(self.portfolio.active_trades.keys()):
                if condition_id in current_condition_ids:
                    continue
                trade = self.portfolio.active_trades[condition_id]
                reference = trade.market.get("open_oracle_price") or trade.entry_spot
                if reference is None:
                    reference = trade.market.get("strike", spot) or spot
                if trade.direction == "YES":
                    exit_price = 1.0 if spot >= reference else 0.0
                else:
                    exit_price = 1.0 if spot < reference else 0.0
                closed = self.portfolio.force_exit(condition_id, exit_price, "expiry_resolve_dropped")
                if closed:
                    net_proceeds = closed.exit_price * closed.net_shares() - closed.exit_fee
                    self.global_pool.release(net_proceeds)
                    self.logger.log_trade(closed.to_dict())
                    self.logger.write_state(self.portfolio.state())
                    self.logger.write_perf(self.portfolio.perf())
        except Exception as exc:
            self.logger.log_event("expired_exit_error", {"error": str(exc), "asset": self.asset})
            self.diag["errors"] += 1

    def _state_dict(self):
        """Portfolio state plus runner metadata so deploy tools can reconcile pools."""
        state = self.portfolio.state()
        if not isinstance(state, dict):
            state = {}
        state["namespace"] = self.namespace
        state["asset"] = self.asset
        state["strategy"] = STRATEGY_NAME
        state["safe_name"] = SAFE_NAME
        return state

    def flush(self):
        try:
            self.logger.write_state(self._state_dict())
            self.logger.write_perf(self.portfolio.perf())
        except Exception as exc:
            self.logger.log_event("logger_flush_error", {"error": str(exc), "asset": self.asset})
            self.diag["errors"] += 1

    def shutdown(self):
        try:
            self.logger.log_event("runner_shutdown", {"strategy": STRATEGY_NAME, "asset": self.asset})
            self.logger.write_state(self._state_dict())
            self.logger.write_perf(self.portfolio.perf())
        except Exception:
            pass


def main():
    global _running

    registry_entry = STRATEGIES[STRATEGY_NAME]
    feed = RedisFeed(host="localhost", port=6379)
    runners = [AssetRunner(asset, registry_entry) for asset in ASSETS]

    while _running:
        loop_start = time.time()
        try:
            for runner in runners:
                if not _running:
                    break
                now = time.time()
                if now - runner.last_heartbeat >= HEARTBEAT_INTERVAL_SECONDS:
                    runner.heartbeat()
                if now - runner.last_discovery >= DISCOVERY_INTERVAL_SECONDS:
                    runner.discover(feed)
                runner.update_spot(feed)
                runner.update_oracle(feed)
                runner.process_markets(feed)
                runner.resolve_dropped_markets(feed)
                runner.flush()
        except Exception as exc:
            # Log to the first runner's logger so a total loop failure is visible.
            runners[0].logger.log_event("main_loop_error", {"error": str(exc)})
            runners[0].diag["errors"] += 1

        elapsed = time.time() - loop_start
        sleep_for = max(0.0, LOOP_SLEEP_SECONDS - elapsed)
        if _running:
            time.sleep(sleep_for)

    for runner in runners:
        runner.shutdown()


if __name__ == "__main__":
    main()
